const rankingPolla = [
  { posicion: 1, cartilla: 70, nombre: "Carlos Moreno Inostroza", puntos: 22, exactos: 5, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 2, cartilla: 30, nombre: "Pablo Velásquez 2 (Amalia Velásquez)", puntos: 21, exactos: 4, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 3, cartilla: 110, nombre: "Ronald Andres Jaque Weiss", puntos: 21, exactos: 4, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 4, cartilla: 4, nombre: "VERONICA ERENCHUN EGUIGUREN", puntos: 19, exactos: 4, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 5, cartilla: 20, nombre: "María Belén Seminario Chesta", puntos: 19, exactos: 4, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 6, cartilla: 87, nombre: "CARLOS MORENO FLORES", puntos: 19, exactos: 4, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 7, cartilla: 17, nombre: "Pendiente revisar nombre", puntos: 18, exactos: 4, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 8, cartilla: 44, nombre: "Cristián Tenorio 2", puntos: 18, exactos: 3, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 9, cartilla: 3, nombre: "GONZALO ERENCHUN SOLER", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 10, cartilla: 35, nombre: "RODRIGO BARRAZA MILLA 2 (NICOLAS BARRAZA SALINAS)", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 11, cartilla: 72, nombre: "Hugo Arancibia (Nicolás Ignacio Arancibia Hoyuela)", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 12, cartilla: 73, nombre: "Luis Vilches 2", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 13, cartilla: 75, nombre: "Pablo Belmar Aedo 2", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 14, cartilla: 92, nombre: "Carlos Seminario 4 (Matías Ignacio Seminario Chetsa)", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 15, cartilla: 95, nombre: "Jean Pierre Margalet 5 (Nicolás Naranjo Olivares - Macarena Margalet)", puntos: 17, exactos: 3, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 16, cartilla: 21, nombre: "LUIS VERGARA HARRIS", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 17, cartilla: 29, nombre: "Pablo Velásquez 1", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 18, cartilla: 55, nombre: "Pedro Benavente Guerrero 2", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 19, cartilla: 96, nombre: "Andrés Cisternas", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 20, cartilla: 98, nombre: "Andrés Cisternas 2", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 21, cartilla: 102, nombre: "Andrés Cisternas 5 (María Jesús Cisternas)", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 22, cartilla: 104, nombre: "Bryan Christopher Torres Valdès", puntos: 16, exactos: 3, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 23, cartilla: 13, nombre: "JUAN DIEGO ELGUETA BENAVENTE", puntos: 16, exactos: 2, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 24, cartilla: 8, nombre: "Claudio Zapata Aburto", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 25, cartilla: 23, nombre: "VIVIANA LOBOS", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 26, cartilla: 31, nombre: "Pablo Velásquez 3 (Alejandra Valenzuela)", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 27, cartilla: 46, nombre: "Miguel Allendes Marchant (2)", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 28, cartilla: 56, nombre: "Amelia Benavente Guerrero", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 29, cartilla: 64, nombre: "Jorge Majmud Miranda", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 30, cartilla: 69, nombre: "Hector Vera Arraño", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 31, cartilla: 74, nombre: "Pablo Belmar Aedo 1", puntos: 15, exactos: 3, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 32, cartilla: 45, nombre: "Miguel Allendes Marchant (1)", puntos: 15, exactos: 2, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 33, cartilla: 76, nombre: "Jorge Ávila", puntos: 15, exactos: 2, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 34, cartilla: 16, nombre: "Pendiente revisar nombre", puntos: 14, exactos: 3, ganadorEmpate: 5, partidosComputados: 20 },
  { posicion: 35, cartilla: 67, nombre: "GABRIEL TENORIO R.", puntos: 14, exactos: 3, ganadorEmpate: 5, partidosComputados: 20 },
  { posicion: 36, cartilla: 38, nombre: "Ignacio Mena 1", puntos: 14, exactos: 2, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 37, cartilla: 53, nombre: "MICHAEL ELIAS ASTORGA OLIVARES", puntos: 14, exactos: 2, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 38, cartilla: 54, nombre: "Pedro Benavente Guerrero", puntos: 14, exactos: 2, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 39, cartilla: 85, nombre: "CARLOS MORENO FLORES", puntos: 14, exactos: 2, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 40, cartilla: 99, nombre: "Patricio Lobos", puntos: 14, exactos: 2, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 41, cartilla: 28, nombre: "Jessica Martínez Ahumada", puntos: 13, exactos: 3, ganadorEmpate: 4, partidosComputados: 20 },
  { posicion: 42, cartilla: 77, nombre: "Efraín Albornoz Tapia (Jefe Laboratorio PLG)", puntos: 13, exactos: 3, ganadorEmpate: 4, partidosComputados: 20 },
  { posicion: 43, cartilla: 107, nombre: "William Malebrán (Jordan Malebrán Donat)", puntos: 13, exactos: 3, ganadorEmpate: 4, partidosComputados: 20 },
  { posicion: 44, cartilla: 12, nombre: "FERNANDO J. ELGUETA LARRAIN", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 45, cartilla: 14, nombre: "Pablo Ferrer Orrego", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 46, cartilla: 34, nombre: "RODRIGO BARRAZA MILLA 1", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 47, cartilla: 40, nombre: "José Pablo Carrillo", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 48, cartilla: 41, nombre: "MARIO MORENO F.", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 49, cartilla: 42, nombre: "RAFAEL ANTONIO PEREZ TORRES", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 50, cartilla: 63, nombre: "Jorge Majmud Miranda", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 51, cartilla: 78, nombre: "Claudio Contreras", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 52, cartilla: 108, nombre: "Antonio Pèrez Cortez", puntos: 13, exactos: 2, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 53, cartilla: 2, nombre: "Javier Mena Isla (Proyecto Saddn)", puntos: 13, exactos: 1, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 54, cartilla: 24, nombre: "RODRIGO LOBOS", puntos: 12, exactos: 2, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 55, cartilla: 62, nombre: "Diego Hinojosa 2 (Claudia Almendra)", puntos: 12, exactos: 2, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 56, cartilla: 66, nombre: "Ignacio Mena 2", puntos: 12, exactos: 2, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 57, cartilla: 106, nombre: "William Andres Malebran Santander", puntos: 12, exactos: 2, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 58, cartilla: 22, nombre: "RICARDO ANDRES", puntos: 12, exactos: 1, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 59, cartilla: 109, nombre: "Pendiente revisar nombre", puntos: 12, exactos: 1, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 60, cartilla: 33, nombre: "Pablo Velásquez 5 (Felipe Velásquez Valenzuela)", puntos: 11, exactos: 2, ganadorEmpate: 5, partidosComputados: 20 },
  { posicion: 61, cartilla: 18, nombre: "Carlos Seminario", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 62, cartilla: 32, nombre: "Pablo Velásquez 4 (Agustina Velásquez)", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 63, cartilla: 43, nombre: "José Antonio Margalet Inglés", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 64, cartilla: 88, nombre: "Magdalena Guerrero 4 (Pedro Benavente Guerrero 3)", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 65, cartilla: 94, nombre: "Jean Pierre Margalet 4 (José Antonio Margalet Olguín )", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 66, cartilla: 97, nombre: "Javier Morales Ugalde", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 67, cartilla: 100, nombre: "Andrés Cisternas 3 (Diego Cisternas)", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 68, cartilla: 101, nombre: "Andrés Cisternas 4 (Sofía Cisternas)", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 69, cartilla: 111, nombre: "Cristian Chulak F.", puntos: 11, exactos: 1, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 70, cartilla: 79, nombre: "Lino Valdivieso", puntos: 11, exactos: 0, ganadorEmpate: 11, partidosComputados: 20 },
  { posicion: 71, cartilla: 25, nombre: "MARIA JOSE", puntos: 10, exactos: 1, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 72, cartilla: 39, nombre: "Hugo Arancibia Bravo", puntos: 10, exactos: 1, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 73, cartilla: 86, nombre: "CARLOS MORENO FLORES", puntos: 10, exactos: 1, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 74, cartilla: 103, nombre: "Gissette Escanilla", puntos: 10, exactos: 1, ganadorEmpate: 7, partidosComputados: 20 },
  { posicion: 75, cartilla: 1, nombre: "CARLOS TAPIA B.", puntos: 10, exactos: 0, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 76, cartilla: 19, nombre: "Andrea Lorena Chesta Carrasco", puntos: 10, exactos: 0, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 77, cartilla: 37, nombre: "Roberto Mena Benavides 2", puntos: 10, exactos: 0, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 78, cartilla: 71, nombre: "Sergio Brito Avila", puntos: 10, exactos: 0, ganadorEmpate: 10, partidosComputados: 20 },
  { posicion: 79, cartilla: 11, nombre: "Javier Ignacio Vergara Kurrer", puntos: 9, exactos: 1, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 80, cartilla: 65, nombre: "LUIS VILCHES", puntos: 9, exactos: 1, ganadorEmpate: 6, partidosComputados: 20 },
  { posicion: 81, cartilla: 7, nombre: "JEAN PIERRE MARGALET INGLÉS", puntos: 9, exactos: 0, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 82, cartilla: 26, nombre: "GIOVANNA MARCONI", puntos: 9, exactos: 0, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 83, cartilla: 61, nombre: "Diego Hinojosa 1", puntos: 9, exactos: 0, ganadorEmpate: 9, partidosComputados: 20 },
  { posicion: 84, cartilla: 15, nombre: "Pendiente revisar nombre", puntos: 8, exactos: 0, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 85, cartilla: 68, nombre: "ALFREDO MENARES BERRIOS", puntos: 8, exactos: 0, ganadorEmpate: 8, partidosComputados: 20 },
  { posicion: 86, cartilla: 36, nombre: "Roberto Mena Benavides 1", puntos: 7, exactos: 0, ganadorEmpate: 7, partidosComputados: 20 }
];

const cartillasPendientesOCR = [
  5, 6, 9, 10, 27, 47, 48, 49, 50, 51, 52, 57, 58, 59, 60, 80, 81, 82, 83, 84, 89, 90, 91, 93, 105
];
